spring.application.name=sistema-fraude-bancaria

spring.datasource.url=jdbc:postgresql://localhost:5432/fraudebancaria
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true